# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org'
# platform :ios, '9.0'
target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    platform :ios, '14.0'  # ios.deploymentTarget
#       pod 'PhoneNumberKit', '~> 3.7'
#
#         pod 'libPhoneNumber-iOS', '~> 0.8'

    pod 'multiplatformContact', :path => '../multiplatformContact'
  # Pods for iosApp

end


